services:
  - type: web
    name: serenity-daily
    runtime: python
    buildCommand: pip install -r requirements-web.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DINGTALK_WEBHOOK
        value: https://oapi.dingtalk.com/robot/send?access_token=271e4d2114e8303b47517a8017f4a4584af66f1c9a999b06a646afd94a6b2c3d
